# Generated by Django 3.0.6 on 2020-05-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200505_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='posts.Category'),
            preserve_default=False,
        ),
    ]
