# Generated by Django 3.0.6 on 2020-05-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='site_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
