# Generated by Django 3.0.6 on 2020-05-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
